### ISSUE TITLE
Separator lines margin error

### ISSUE THREAD

**Issue by MarceloCavaco** [WithoutHaste/Pinker#7]
hi, i found a error when use separator (pipe)

the line not consider the margin.

im do something wrong???

print img:
https://drive.google.com/open?id=15PjKkHd5Cr2nE9pF60CNyDXEVoiyCeDx

the source:
```
<pre id="sourcePinker_atributo" style="display:none;">
Layout:
	[{A}Atributo]
	[{B}atributo_item]
Relate:
	{A}-&gt;{B}
{A}:
	Define:
		id_organizacao (Organização) - Int
		id_atributo (Código) - Int|
		ds_atributo (Descrição) - String(30)
		dt_atualizacao (Alteração) - String(20)
{B}:
	Define:
		id_organizacao (Organização) - Int
		id_atributo (Atributo) - Int
		id_atributo_item (Código) - Int|
		dt_atualizacao (Data de Alteração) - Date(10)
		ds_atributo_item (Descrição) - String(30)
</pre>
```

**Comment by WithoutHaste** [comment]
Hi, are you using any custom settings?  I have not been able to reproduce the bug with the default settings.

Your syntax is correct, so the problem is definitely in Pinker.

**Comment by WithoutHaste** [comment]
I've reproduced the error. Working on it...

**Comment by MarceloCavaco** [comment]
tkx...

**Comment by WithoutHaste** [comment]
Cause of error: 
When setting favorUniformNodeSizes:true
DefineLayout.draw assumed that the text area would be horizontally centered in the node, so it centered the dividing line over the text area.
